version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile

    entrypoint: "/app/run_server.sh"
    ports:
      - "80:8000"
    env_file:
      - .env
    volumes:
      - .:/app/
    restart: "on-failure"
    depends_on:
      - db
      - redis

  db:
    image: postgres:11-alpine
    volumes:
      - ~/pgsql/quiz_bot:/var/lib/postgresql/data/

    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - PGPORT=5432
      - POSTGRES_USER=postgres

    restart: "on-failure"

 # Redis
  redis:
    image: redis
    hostname: redis
